CREATE TABLE `products` (
	`serial` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`maker` text NOT NULL,
	`lot` text NOT NULL,
	`expiry` text NOT NULL,
	`status` text NOT NULL,
	`brand` text DEFAULT '' NOT NULL
);
--> statement-breakpoint
DROP INDEX `idx_verification_profile_serial_time`;--> statement-breakpoint
CREATE INDEX `idx_verification_profile_serial_time` ON `verification_events` (`profile_id`,`serial`,`activated_at`);
--> statement-breakpoint
UPDATE customer_profiles SET serials_json='[]' WHERE NOT json_valid(serials_json);
--> statement-breakpoint
UPDATE customer_profiles SET revoked_serials_json='[]' WHERE NOT json_valid(revoked_serials_json);
--> statement-breakpoint
UPDATE customer_profiles SET benefits_json='[]' WHERE NOT json_valid(benefits_json);
--> statement-breakpoint
UPDATE customer_profiles SET verified_at_json='{}' WHERE NOT json_valid(verified_at_json);
--> statement-breakpoint
UPDATE customer_profiles SET consent_json='{}' WHERE NOT json_valid(consent_json);
--> statement-breakpoint
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('35172','Lipoless 2,5mg','Eticos','SC-ETIC-26001','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('47060','Mounjaro Lilly 15mg original','Farmacia','SC-FARM-26002','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('62529','Retatrutida 16mg','Health Peptides','SC-HEAL-26003','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('67728','Retatrutida 30mg','GEN','SC-GEN-26004','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('40563','T.G 10mg','Indufar','SC-INDU-26005','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('31847','Tirzec 2,5mg','Quimfa S.A','SC-QUIM-26006','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('44793','Retatrutida 10mg','Neuroceptix','SC-NEUR-26007','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('83135','Retatrutida 40mg','Royalpharmaceutical','SC-ROYA-26008','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('27047','Retatrutida Caneta 40mg','Synedica','SC-SYNE-26009','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('95788','Euro gold 240ui','Variados','SC-VARI-26010','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('82752','Retratutida bujão 40mg','ZPHCD','SC-ZPHC-26011','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('50253','Lipoland 10mg','Landergold','SC-LAND-26012','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('50040','Retratutida 30mg','Slimedic','SC-SLIM-26013','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('68550','Primobolan 10ml','AlphaPharma','SC-ALPH-26014','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('22917','Adipodite 5mg','Better Peptídeos','SC-BETT-26015','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('60706','Bold 200mg','Canada Labs','SC-CANA-26016','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('51965','GH 100ui','Cooper Pharma','SC-COOP-26017','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('62157','Clembuterol 40mcg','Eminence Labs','SC-EMIN-26018','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('82093','Dimorf 50Cp 10mg','Farmácia Nacional','SC-FARM-26019','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('55448','Anavar 10mg','King Pharma','SC-KING-26020','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('47170','Dhea 25mg','Lander Fit','SC-LAND-26021','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('57281','Dura ampola 1ml','Landerlan','SC-LAND-26022','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('88162','Cafeína 60cp 210mg','Manipulados','SC-MANI-26023','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('13992','Durateston 1ml','Muscle Pharma','SC-MUSC-26024','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('59122','Cipionato 5ml','Muscle Pharma Black','SC-MUSC-26025','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('23741','Adipotide 5mg','Health Peptídeos','SC-HEAL-26026','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('91598','Água bacteriostático 3ml','Peptídeos Neuroceptix','SC-PEPT-26027','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('37079','Deca 300mg','Royal Pharmaceutical','SC-ROYA-26028','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('65630','Oxan 5mg','RX Pharmaceuticals','SC-RXPH-26029','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('90440','Aod 5mg','ZPHC','SC-ZPHC-26030','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('58475','Oxan 20mg','Pharmaplix','SC-PHAR-26031','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('82049','Lipoless 5mg','Eticos','SC-ETIC-26032','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('99445','Retatrutida 40mg','Health Peptides','SC-HEAL-26033','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('77735','Retatrutida 40mg','GEN','SC-GEN-26034','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('11348','T.G 12mg','Indufar','SC-INDU-26035','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('44187','Tirzec 5mg','Quimfa S.A','SC-QUIM-26036','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('90132','Retatrutida 20mg','Neuroceptix','SC-NEUR-26037','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('35904','Semaglutida 10mg','Royalpharmaceutical','SC-ROYA-26038','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('26407','Tirzepatida Caneta 40mg','Synedica','SC-SYNE-26039','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('88912','Retatrutida caneta ALLUVI 40mg','Variados','SC-VARI-26040','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('18313','Retatrutida caneta 30mg','ZPHCD','SC-ZPHC-26041','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('27851','Lipoland 15mg','Landergold','SC-LAND-26042','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('48223','Tirzepatida 30mg','Slimedic','SC-SLIM-26043','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('17237','Stano injetável 10ml','AlphaPharma','SC-ALPH-26044','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('67699','BPC157 5mg','Better Peptídeos','SC-BETT-26045','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('42029','Bold 300mg','Canada Labs','SC-CANA-26046','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('51836','Hgh frag 2mg','Cooper Pharma','SC-COOP-26047','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('41726','Clembuterol 60mcg','Eminence Labs','SC-EMIN-26048','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('18487','Fluoxetina 20Mg','Farmácia Nacional','SC-FARM-26049','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('58076','Anavar 20mg','King Pharma','SC-KING-26050','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('81161','Melatonina 5mg','Lander Fit','SC-LAND-26051','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('68719','Oxandrolona 10mg','Landerlan','SC-LAND-26052','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('19623','Ioimbina 60cp 10mg','Manipulados','SC-MANI-26053','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('92627','GH Somatropin 50ui','Muscle Pharma','SC-MUSC-26054','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('35574','Primobolan 5ml','Muscle Pharma Black','SC-MUSC-26055','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('33999','Amino 5mg','Health Peptídeos','SC-HEAL-26056','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('62068','Água bacteriostático 10ml','Peptídeos Neuroceptix','SC-PEPT-26057','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('96300','Super testo 400mg','Royal Pharmaceutical','SC-ROYA-26058','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('83257','Oxan 10mg','RX Pharmaceuticals','SC-RXPH-26059','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('59165','BPC157 5mg','ZPHC','SC-ZPHC-26060','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('91704','Lipoless 7,5mg','Eticos','SC-ETIC-26061','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('27962','Tirzepatida 20mg','Health Peptides','SC-HEAL-26062','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('21940','Retatrutida 50mg','GEN','SC-GEN-26063','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('40890','T.G 15mg','Indufar','SC-INDU-26064','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('50565','Tirzec 7,5mg','Quimfa S.A','SC-QUIM-26065','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('15475','Retatrutida 40mg','Neuroceptix','SC-NEUR-26066','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('47314','Tirzepatida 30mg','Royalpharmaceutical','SC-ROYA-26067','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('95211','Semaglutida semaglix 1,34mg','Variados','SC-VARI-26068','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('85116','Semaglutida 5mg','ZPHCD','SC-ZPHC-26069','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('16143','Tirzepatida 60mg','Slimedic','SC-SLIM-26070','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('22213','Ghrp6 5mg','Better Peptídeos','SC-BETT-26071','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('93938','Gh 75ui','Canada Labs','SC-CANA-26072','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('25960','Igf1 1mg','Cooper Pharma','SC-COOP-26073','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('19261','HCG 5000ui','Eminence Labs','SC-EMIN-26074','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('85650','GH biomanguinho 12ui','Farmácia Nacional','SC-FARM-26075','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('89174','Anavar 5mg','King Pharma','SC-KING-26076','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('82810','Melatonina 10mg','Lander Fit','SC-LAND-26077','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('40894','Oxandrolona 5mg','Landerlan','SC-LAND-26078','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('20669','Minoxidil 1mg','Manipulados','SC-MANI-26079','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('85748','Hemogenin oral 25mg','Muscle Pharma','SC-MUSC-26080','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('86893','Sustan 10ml','Muscle Pharma Black','SC-MUSC-26081','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('94877','Amino 10mg','Health Peptídeos','SC-HEAL-26082','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('33666','Aod-9604 5mg','Peptídeos Neuroceptix','SC-PEPT-26083','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('20491','Oxan 20mg','RX Pharmaceuticals','SC-RXPH-26084','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('96386','Caneta GH 180ui','ZPHC','SC-ZPHC-26085','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('22893','Lipoless 10mg','Eticos','SC-ETIC-26086','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('72751','Tirzepatida 60mg','Health Peptides','SC-HEAL-26087','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('95882','Retatrutida 60mg','GEN','SC-GEN-26088','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('47441','Tirzec 10mg','Quimfa S.A','SC-QUIM-26089','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('16589','Tirzepatida 10mg','Neuroceptix','SC-NEUR-26090','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('76121','Água bacteriostático 10ml','Variados','SC-VARI-26091','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('44153','Tirzepatida 10mg','ZPHCD','SC-ZPHC-26092','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('63539','Hgh frag 5mg','Better Peptídeos','SC-BETT-26093','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('40432','Stano 100mg','Cooper Pharma','SC-COOP-26094','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('45235','Rivotril 2mg comp','Farmácia Nacional','SC-FARM-26095','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('44336','Stano 15ml','King Pharma','SC-KING-26096','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('47963','Primobolan 10ml','Landerlan','SC-LAND-26097','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('10637','Oxan 10mg Sinergy','Manipulados','SC-MANI-26098','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('59566','Oxandrolona 10mg','Muscle Pharma','SC-MUSC-26099','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('58163','T250 5ml','Muscle Pharma Black','SC-MUSC-26100','12/2027','authentic','');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('37179','Lipoless 12,5mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-101','12/2027','authentic','Eticos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('19488','Lipoless 15mg','Farmácia MG — Uberlândia','SC-MG-UDI-102','12/2027','authentic','Eticos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('93395','Tirzepatida 90mg','Farmácia MG — Contagem','SC-MG-CTG-103','12/2027','authentic','Health Peptides');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('85599','Tirzepatida 15mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-104','12/2027','authentic','GEN');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('36160','Tirzepatida 40mg','Farmácia MG — Betim','SC-MG-BTM-105','12/2027','authentic','GEN');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('97311','Tirzepatida 70mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-106','12/2027','authentic','GEN');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('84145','Tirzepatida 80mg','Farmácia MG — Uberlândia','SC-MG-UDI-107','12/2027','authentic','GEN');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('27270','Tirzec 15mg','Farmácia MG — Contagem','SC-MG-CTG-108','12/2027','authentic','Quimfa S.A');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('24708','Tirzepatida 5mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-109','12/2027','authentic','ZPHCD');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('61103','Tirzepatida 7,5mg','Farmácia MG — Betim','SC-MG-BTM-110','12/2027','authentic','ZPHCD');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('10451','Tirzepatida caneta 30mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-111','12/2027','authentic','ZPHCD');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('94317','Ipamorelin 5mg','Farmácia MG — Uberlândia','SC-MG-UDI-112','12/2027','authentic','Better Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('88483','TB500 5mg','Farmácia MG — Contagem','SC-MG-CTG-113','12/2027','authentic','Better Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('13616','Stano 50mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-114','12/2027','authentic','Cooper Pharma');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('26264','Dhea25mg','Farmácia MG — Betim','SC-MG-BTM-115','12/2027','authentic','Dragon Elite Sarms');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('61191','Dhea50mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-116','12/2027','authentic','Dragon Elite Sarms');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('53724','Dhea100mg','Farmácia MG — Uberlândia','SC-MG-UDI-117','12/2027','authentic','Dragon Elite Sarms');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('54757','Criscy12ui','Farmácia MG — Contagem','SC-MG-CTG-118','12/2027','authentic','Farmácia Nacional');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('73670','Rivotril 2mg got','Farmácia MG — Juiz de Fora','SC-MG-JDF-119','12/2027','authentic','Farmácia Nacional');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('56425','Sibutramina 15mg','Farmácia MG — Betim','SC-MG-BTM-120','12/2027','authentic','Farmácia Nacional');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('23685','Tadalafila 5mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-121','12/2027','authentic','Farmácia Nacional');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('41876','Tamoxifeno 20mg','Farmácia MG — Uberlândia','SC-MG-UDI-122','12/2027','authentic','Farmácia Nacional');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('79968','Stano 30ml','Farmácia MG — Contagem','SC-MG-CTG-123','12/2027','authentic','King Pharma');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('41330','Testenat 4ml','Farmácia MG — Juiz de Fora','SC-MG-JDF-124','12/2027','authentic','Landerlan');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('19263','Oxan 20mg Sinergy','Farmácia MG — Betim','SC-MG-BTM-125','12/2027','authentic','Manipulados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('28800','Similarina 200mg 30cp','Farmácia MG — Belo Horizonte','SC-MG-BHZ-126','12/2027','authentic','Manipulados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('50950','Venvanse10mg','Farmácia MG — Uberlândia','SC-MG-UDI-127','12/2027','authentic','Manipulados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('51384','Venvanse30mg','Farmácia MG — Contagem','SC-MG-CTG-128','12/2027','authentic','Manipulados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('64569','Venvanse50mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-129','12/2027','authentic','Manipulados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('45240','Venvanse70mg','Farmácia MG — Betim','SC-MG-BTM-130','12/2027','authentic','Manipulados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('54131','Oxandrolona 25mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-131','12/2027','authentic','Muscle Pharma');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('93901','Stano 30ml aquoso','Farmácia MG — Uberlândia','SC-MG-UDI-132','12/2027','authentic','Muscle Pharma');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('76471','Winstrol 10ml 100mg','Farmácia MG — Contagem','SC-MG-CTG-133','12/2027','authentic','Muscle Pharma');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('92992','BPC-157 10mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-134','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('12937','CJC NO DAC 5mg','Farmácia MG — Betim','SC-MG-BTM-135','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('14932','DSIP 15mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-136','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('74825','GH 15ui','Farmácia MG — Uberlândia','SC-MG-UDI-137','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('32542','GHK-Cu 50mg','Farmácia MG — Contagem','SC-MG-CTG-138','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('81466','GHRP6 10mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-139','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('53739','Igf DÊS 1mg','Farmácia MG — Betim','SC-MG-BTM-140','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('38456','Igf LR3 1mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-141','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('61060','Ipamorelin 10mg','Farmácia MG — Uberlândia','SC-MG-UDI-142','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('22552','KPV 10mg','Farmácia MG — Contagem','SC-MG-CTG-143','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('34195','Melatonan II 10mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-144','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('50743','Mots-c 10mg','Farmácia MG — Betim','SC-MG-BTM-145','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('75208','Nadh 500mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-146','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('40249','PT-141 10mg','Farmácia MG — Uberlândia','SC-MG-UDI-147','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('41166','Retratutida 16mg','Farmácia MG — Contagem','SC-MG-CTG-148','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('65943','Retratutida 40mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-149','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('24572','SLUPP-332 5mg','Farmácia MG — Betim','SC-MG-BTM-150','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('66922','SS31 10mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-151','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('95436','TB500 10mg','Farmácia MG — Uberlândia','SC-MG-UDI-152','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('59322','Tesamorelin 10mg','Farmácia MG — Contagem','SC-MG-CTG-153','12/2027','authentic','Health Peptídeos');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('47858','BPC+TB500 20mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-154','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('66958','Bpc-157 5mg','Farmácia MG — Betim','SC-MG-BTM-155','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('28660','Bpc-157 + tb500 10mg.','Farmácia MG — Belo Horizonte','SC-MG-BHZ-156','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('89606','Cjc SEM DAC 5mg','Farmácia MG — Uberlândia','SC-MG-UDI-157','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('17616','CJC1295 +Ipamorelin10mg','Farmácia MG — Contagem','SC-MG-CTG-158','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('93675','DSIP 5mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-159','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('70034','Epithalon 50mg','Farmácia MG — Betim','SC-MG-BTM-160','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('74354','Ghrp2 5mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-161','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('94145','Glow 70mg','Farmácia MG — Uberlândia','SC-MG-UDI-162','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('83410','Igf1 DÊS 1mg','Farmácia MG — Contagem','SC-MG-CTG-163','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('50601','Igf1 LR3 1mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-164','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('50571','KissPeptin 10mg','Farmácia MG — Betim','SC-MG-BTM-165','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('68976','KLOW 80mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-166','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('46404','LipoC + LipoB 216mg','Farmácia MG — Uberlândia','SC-MG-UDI-167','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('28122','Melatonan2 10mg','Farmácia MG — Contagem','SC-MG-CTG-168','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('47979','MOTS-C 40mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-169','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('66612','NAD+ 500mg','Farmácia MG — Betim','SC-MG-BTM-170','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('94040','PEG-MGF 2mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-171','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('33088','Retratutida 10mg','Farmácia MG — Uberlândia','SC-MG-UDI-172','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('19151','Retratutida 20mg.','Farmácia MG — Contagem','SC-MG-CTG-173','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('63615','Selank 5mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-174','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('16077','Selank 10mg','Farmácia MG — Betim','SC-MG-BTM-175','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('78000','Semax 5mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-176','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('94243','Semax 10mg','Farmácia MG — Uberlândia','SC-MG-UDI-177','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('90236','Slu-PP-332 5mg','Farmácia MG — Contagem','SC-MG-CTG-178','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('12857','SS31 50mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-179','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('69969','Tesamorelin 5mg','Farmácia MG — Betim','SC-MG-BTM-180','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('33740','VIP 10mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-181','12/2027','authentic','Peptídeos Neuroceptix');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('35466','Bold300mg','Farmácia MG — Uberlândia','SC-MG-UDI-182','12/2027','authentic','Pharmacom Labs');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('75153','Bold500mg','Farmácia MG — Contagem','SC-MG-CTG-183','12/2027','authentic','Pharmacom Labs');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('64133','Deca300mg','Farmácia MG — Juiz de Fora','SC-MG-JDF-184','12/2027','authentic','Pharmacom Labs');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('61619','Deca600mg','Farmácia MG — Betim','SC-MG-BTM-185','12/2027','authentic','Pharmacom Labs');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('54451','Dura300mg','Farmácia MG — Belo Horizonte','SC-MG-BHZ-186','12/2027','authentic','Pharmacom Labs');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('22655','Primo200mg','Farmácia MG — Uberlândia','SC-MG-UDI-187','12/2027','authentic','Pharmacom Labs');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('78287','Stano 30ml oleoso','Farmácia MG — Contagem','SC-MG-CTG-188','12/2027','authentic','RX Pharmaceuticals');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('36557','Água bacteriostático 2ml','Farmácia MG — Juiz de Fora','SC-MG-JDF-189','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('62188','Botox Israderm 100ui','Farmácia MG — Betim','SC-MG-BTM-190','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('43364','Caneta 300ui','Farmácia MG — Belo Horizonte','SC-MG-BHZ-191','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('64708','Caneta nordtrooin 90ui','Farmácia MG — Uberlândia','SC-MG-UDI-192','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('37688','Kigtropin caneta200ui','Farmácia MG — Contagem','SC-MG-CTG-193','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('54142','Melatonina 10mg EP','Farmácia MG — Juiz de Fora','SC-MG-JDF-194','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('67365','Melatonina 5mg EP','Farmácia MG — Betim','SC-MG-BTM-195','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('87692','Tadalafila 10mg EP','Farmácia MG — Belo Horizonte','SC-MG-BHZ-196','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('61210','Tadalafila 20mg EP','Farmácia MG — Uberlândia','SC-MG-UDI-197','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('24105','Tadalafila 5mg EP','Farmácia MG — Contagem','SC-MG-CTG-198','12/2027','authentic','Variados');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('91048','Deca Bujão 30ml','Farmácia MG — Juiz de Fora','SC-MG-JDF-199','12/2027','authentic','ZPHC');
INSERT INTO products (serial,name,maker,lot,expiry,status,brand) VALUES ('69693','Enan400mg','Farmácia MG — Betim','SC-MG-BTM-200','12/2027','authentic','ZPHC');
