-- Accessory products added on the owner's request (2026-09-29) to widen the
-- catalog and allow low-value test purchases: priced R$ 5 / 20 / 30 / 50 on
-- purpose (Pix minimum is R$ 5; crypto minimum R$ 20). The sharps collector
-- comes in two sizes (1 L and 3 L), both R$ 20. Raise prices in the admin
-- (Loja → Catálogo) once payment testing is over. Category `acessorios` only:
-- vials stay non-purchasable (REGULATED_CATEGORIES). No ratings/reviews (none
-- exist yet) and no registration numbers: confirm the real manufacturer's
-- ANVISA regularization before selling syringes/needles
-- (docs/loja-revisao-regulatoria.md). Images in public/loja are
-- the owner's own product photos (converted to webp).
-- 
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('seringas-1ml-31g', 'seringas-1ml-31g-cx10', 10, 'Save Concept', 'Seringas 1ml com Agulha 31G', 'Caixa com 100 unidades · 31G', 'acessorios', 'Seringas de 1ml com agulha ultrafina 31G acoplada, estéreis e de uso único.', 'Seringa de 1ml com agulha fixa 31G (0,25 mm), ultrafina, e escala precisa. Estéril, atóxica, apirogênica e de uso único. Descarte após o uso em coletor de perfurocortantes.', 20.0, NULL, '{"count": 100, "label": "seringa"}', 'Novo', 0, 0, '["100 seringas, uso único", "Capacidade: 1ml, com escala precisa", "Agulha fixa 31G (0,25 mm), ultrafina", "Estéril, atóxica e apirogênica"]', 1, 1, 1, 0, 1, '{"base": "/loja/seringas-31g", "alt": "Caixa de seringas Save Concept 1ml 31G com 100 unidades e seringas ao lado", "width": 960, "height": 960}', '["seringa", "seringas", "1ml", "31g", "agulha", "insulina", "acessorio"]', '["agulhas-caneta-32g", "lencos-alcool-70", "coletor-perfurocortantes-1l"]', '["lencos-alcool-70", "coletor-perfurocortantes-1l"]', '2026-09-29T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('agulhas-caneta-32g', 'agulhas-caneta-32g-cx100', 11, 'Save Concept', 'Agulhas para Caneta 32G', 'Caixa com 100 unidades · 0,23 mm', 'acessorios', 'Agulhas ultrafinas para canetas aplicadoras, compatíveis com as principais do mercado.', 'Agulhas ultrafinas 32G (0,23 mm), compatíveis com as principais canetas aplicadoras do mercado. Estéreis, apirogênicas e de uso único. Descarte após o uso em coletor de perfurocortantes.', 50.0, NULL, '{"count": 100, "label": "agulha"}', 'Novo', 0, 0, '["100 agulhas, uso único", "Calibre 32G (0,23 mm), ultrafina", "Compatível com as principais canetas do mercado", "Estéril e apirogênica"]', 1, 1, 1, 0, 1, '{"base": "/loja/agulhas-caneta-32g", "alt": "Caixa de agulhas para caneta Save Concept 32G com 100 unidades e agulhas ao lado", "width": 960, "height": 960}', '["agulha", "agulhas", "caneta", "32g", "ultrafina", "pen", "acessorio"]', '["seringas-1ml-31g", "lencos-alcool-70", "coletor-perfurocortantes-1l"]', '["lencos-alcool-70", "coletor-perfurocortantes-1l"]', '2026-09-29T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('lencos-alcool-70', 'lencos-alcool-70-cx100', 12, 'Save Concept', 'Lenços com Álcool 70%', 'Caixa com 100 sachês', 'acessorios', 'Sachês individuais com lenço umedecido em álcool isopropílico 70%.', 'Lenços umedecidos em álcool 70% em sachês individuais, práticos para higienizar a pele e a tampa dos frascos antes do uso.', 5.0, NULL, '{"count": 100, "label": "sachê"}', 'Novo', 0, 0, '["100 sachês individuais", "Álcool 70%", "Secagem rápida", "Uso externo"]', 1, 1, 1, 0, 0, '{"base": "/loja/lencos-alcool", "alt": "Caixa de lenços com álcool 70% Save Concept com 100 unidades e sachês ao lado", "width": 960, "height": 960}', '["lenco", "lencos", "alcool", "70", "sache", "higienizacao", "acessorio"]', '["seringas-1ml-31g", "agulhas-caneta-32g", "kit-aplicacao-premium"]', '["seringas-1ml-31g"]', '2026-09-29T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('coletor-perfurocortantes-1l', 'coletor-perfurocortantes-1l', 13, 'Save Concept', 'Coletor de Perfurocortantes 1 L', 'Unidade · 1 litro', 'acessorios', 'Recipiente rígido e compacto, com tampa, para descarte seguro de agulhas e seringas.', 'Coletor rígido e resistente a perfurações para descartar agulhas e seringas usadas com segurança. Quando atingir a linha de enchimento, feche a tampa e entregue em um posto de coleta (UBS ou farmácia participante).', 20.0, NULL, NULL, 'Novo', 0, 0, '["Capacidade: 1 litro", "Material rígido, resistente a perfurações", "Tampa com trava definitiva", "Linha de enchimento indicada"]', 1, 1, 1, 0, 0, '{"base": "/loja/coletor-perfurocortantes-1l", "alt": "Coletor de perfurocortantes Save Concept de 1 litro, amarelo, com tampa", "width": 960, "height": 960}', '["coletor", "descarte", "perfurocortante", "agulhas usadas", "descarpack", "1 litro", "acessorio"]', '["coletor-perfurocortantes-3l", "seringas-1ml-31g", "agulhas-caneta-32g"]', '["seringas-1ml-31g"]', '2026-09-29T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('coletor-perfurocortantes-3l', 'coletor-perfurocortantes-3l', 14, 'Save Concept', 'Coletor de Perfurocortantes 3 L', 'Unidade · 3 litros', 'acessorios', 'Recipiente rígido de 3 litros, com tampa, para quem descarta mais agulhas e seringas.', 'Coletor rígido e resistente a perfurações para descartar agulhas e seringas usadas com segurança. Quando atingir a linha de enchimento, feche a tampa e entregue em um posto de coleta (UBS ou farmácia participante).', 20.0, NULL, NULL, 'Novo', 0, 0, '["Capacidade: 3 litros", "Material rígido, resistente a perfurações", "Tampa com trava definitiva", "Linha de enchimento indicada"]', 1, 1, 1, 0, 0, '{"base": "/loja/coletor-perfurocortantes-3l", "alt": "Coletor de perfurocortantes Save Concept de 3 litros, amarelo, com a caixa ao lado", "width": 960, "height": 960}', '["coletor", "descarte", "perfurocortante", "agulhas usadas", "descarpack", "3 litros", "acessorio"]', '["coletor-perfurocortantes-1l", "seringas-1ml-31g", "agulhas-caneta-32g"]', '["agulhas-caneta-32g"]', '2026-09-29T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('bolsa-termica-gel', 'bolsa-termica-gel', 15, 'Save Concept', 'Bolsa Térmica com Gel Reutilizável', 'Bolsa térmica + gel térmico reutilizável', 'acessorios', 'Bolsa térmica com gel reutilizável para transportar frascos e canetas refrigerados.', 'Bolsa térmica com revestimento interno de alta eficiência e gel térmico reutilizável, para transportar frascos e canetas refrigerados com segurança. Congele o gel antes do uso.', 30.0, NULL, NULL, 'Novo', 0, 0, '["Dimensões aproximadas: 24 × 19 × 16 cm", "Gel térmico reutilizável de 250 g", "Revestimento térmico interno", "Alças para transporte"]', 1, 1, 1, 0, 0, '{"base": "/loja/bolsa-termica-gel", "alt": "Bolsa térmica preta Save Concept com gel térmico reutilizável e gelo", "width": 960, "height": 960}', '["bolsa", "termica", "gel", "viagem", "refrigerado", "2-8", "acessorio"]', '["kit-aplicacao-premium", "diluente-bacteriostatico"]', '["kit-aplicacao-premium"]', '2026-09-29T00:00:00.000Z', 'migration');
