-- Accessory products added on the owner's request (2026-09-29) to widen the
-- catalog and allow low-value test purchases: priced R$ 5 / 10 / 20 / 30 / 50
-- on purpose (Pix minimum is R$ 5; crypto minimum R$ 20, so 20/30/50 cover
-- it) — raise them in the admin (Loja → Catálogo) once testing is over. Category `acessorios` only: vials
-- stay non-purchasable (REGULATED_CATEGORIES). No ratings/reviews (none exist
-- yet) and no registration numbers: confirm the real manufacturer's ANVISA
-- regularization before selling syringes/needles (docs/loja-revisao-regulatoria.md).
-- Illustrations in public/loja are placeholders to be replaced by real photos.
-- INSERT OR IGNORE: re-running never overwrites edits made in the admin.
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('seringas-1ml-31g', 'seringas-1ml-31g-cx10', 10, 'Save Concept', 'Seringas 1ml com Agulha 31G', 'Caixa com 10 unidades · 31G × 6mm', 'acessorios', 'Seringas de 1ml com agulha fina 31G acoplada, estéreis e embaladas uma a uma.', 'Seringa de 1ml graduada em 100 unidades, com agulha 31G × 6mm fixa (sem espaço morto). Estéril, de uso único e embalada individualmente. Descarte após o uso em coletor de perfurocortantes.', 20.0, NULL, '{"count": 10, "label": "seringa"}', 'Novo', 0, 0, '["10 seringas estéreis, uso único", "Capacidade: 1ml, graduação em 100 unidades", "Agulha fixa 31G × 6mm", "Embalagem individual"]', 1, 1, 1, 0, 1, '{"base": "/loja/seringas-31g", "alt": "Caixa de seringas de 1ml com agulha 31G, com uma seringa ao lado", "width": 960, "height": 960}', '["seringa", "seringas", "1ml", "31g", "agulha", "insulina", "acessorio"]', '["agulhas-caneta-32g-4mm", "lencos-alcool-70", "coletor-perfurocortantes-1-5l"]', '["lencos-alcool-70", "coletor-perfurocortantes-1-5l"]', '2026-09-29T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('agulhas-caneta-32g-4mm', 'agulhas-caneta-32g-4mm-cx100', 11, 'Save Concept', 'Agulhas para Caneta 32G · 4mm', 'Caixa com 100 unidades', 'acessorios', 'Agulhas descartáveis para canetas aplicadoras, com rosca universal.', 'Agulhas de 32G × 4mm com rosca universal, compatíveis com as canetas aplicadoras mais comuns do mercado. Estéreis, de uso único, com lacre individual. Descarte após o uso em coletor de perfurocortantes.', 50.0, NULL, '{"count": 100, "label": "agulha"}', 'Novo', 0, 0, '["100 agulhas estéreis, uso único", "Calibre 32G, comprimento 4mm", "Rosca universal para canetas", "Lacre individual"]', 1, 1, 1, 0, 1, '{"base": "/loja/agulhas-caneta-32g", "alt": "Caixa de agulhas para caneta 32G com três agulhas ao lado", "width": 960, "height": 960}', '["agulha", "agulhas", "caneta", "32g", "4mm", "pen", "acessorio"]', '["seringas-1ml-31g", "lencos-alcool-70", "coletor-perfurocortantes-1-5l"]', '["lencos-alcool-70", "coletor-perfurocortantes-1-5l"]', '2026-09-29T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('lencos-alcool-70', 'lencos-alcool-70-cx100', 12, 'Save Concept', 'Lenços com Álcool 70%', 'Pacote com 10 sachês', 'acessorios', 'Sachês individuais com lenço umedecido em álcool isopropílico 70%.', 'Lenços umedecidos em álcool 70% em sachês individuais, práticos para higienizar a pele e a tampa dos frascos antes do uso.', 5.0, NULL, '{"count": 10, "label": "sachê"}', 'Novo', 0, 0, '["10 sachês individuais", "Álcool isopropílico 70%", "Tamanho do lenço: 3 × 6,5 cm", "Uso externo"]', 1, 1, 1, 0, 0, '{"base": "/loja/lencos-alcool", "alt": "Pacote de lenços com álcool 70% e dois sachês", "width": 960, "height": 960}', '["lenco", "lencos", "alcool", "70", "sache", "higienizacao", "acessorio"]', '["seringas-1ml-31g", "agulhas-caneta-32g-4mm", "kit-aplicacao-premium"]', '["seringas-1ml-31g"]', '2026-09-29T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('coletor-perfurocortantes-1-5l', 'coletor-perfurocortantes-1-5l', 13, 'Save Concept', 'Coletor de Perfurocortantes 1,5 L', 'Unidade · 1,5 litro', 'acessorios', 'Recipiente rígido com tampa para descarte seguro de agulhas e seringas.', 'Coletor rígido e resistente a perfurações para descartar agulhas e seringas usadas com segurança. Quando atingir a linha de enchimento, feche a tampa e entregue em um posto de coleta (UBS ou farmácia participante).', 10.0, NULL, NULL, 'Novo', 0, 0, '["Capacidade: 1,5 litro", "Material rígido, resistente a perfurações", "Tampa com trava definitiva", "Linha de enchimento indicada"]', 1, 1, 1, 0, 0, '{"base": "/loja/coletor-perfurocortantes", "alt": "Coletor amarelo de perfurocortantes com tampa azul", "width": 960, "height": 960}', '["coletor", "descarte", "perfurocortante", "agulhas usadas", "descarpack", "acessorio"]', '["seringas-1ml-31g", "agulhas-caneta-32g-4mm"]', '["seringas-1ml-31g"]', '2026-09-29T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('bolsa-termica-gel', 'bolsa-termica-gel', 14, 'Save Concept', 'Bolsa Térmica com Gel Reutilizável', 'Bolsa compacta + 2 placas de gel', 'acessorios', 'Bolsa térmica compacta com duas placas de gel para transportar frascos e canetas refrigerados.', 'Bolsa térmica compacta com forro isolante e duas placas de gel reutilizáveis. Ajuda a manter frascos e canetas refrigerados durante deslocamentos curtos. Congele as placas por 8 horas antes do uso.', 30.0, NULL, NULL, 'Novo', 0, 0, '["Inclui 2 placas de gel reutilizáveis", "Forro térmico isolante", "Tamanho: 20 × 12 × 8 cm", "Congelar o gel 8h antes do uso"]', 1, 1, 1, 0, 0, '{"base": "/loja/bolsa-termica-gel", "alt": "Bolsa térmica azul Save Concept com placa de gel", "width": 960, "height": 960}', '["bolsa", "termica", "gel", "viagem", "refrigerado", "2-8", "acessorio"]', '["kit-aplicacao-premium", "diluente-bacteriostatico"]', '["kit-aplicacao-premium"]', '2026-09-29T00:00:00.000Z', 'migration');
