-- Three peptides added on the owner's request (2026-09-30) as a study
-- showcase ("vitrine de estudos"): category `frascos`, so they stay
-- display-only exactly like the Tirzepatida/Retatrutida vials —
-- purchasable = 0, and REGULATED_CATEGORIES makes both the admin API and
-- createOrder refuse to sell them. No dosing, route of administration or
-- therapeutic claims in the copy; no ratings/reviews; no "Compre junto".
-- Images in public/loja are illustrations (captioned "IMAGEM ILUSTRATIVA")
-- until the owner sends real photos. Reference prices confirmed by the
-- owner on 2026-09-30; edit them in the admin (Loja → Catálogo).
--
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('bpc-157-5mg', 'bpc-157-5mg-frasco', 5, 'Save Concept', 'BPC-157 5mg', 'Frasco · 5mg, pó liofilizado', 'frascos', 'Peptídeo sintético liofilizado em frasco de 5mg, na vitrine apenas para consulta e estudo.', 'O BPC-157 é um peptídeo sintético de 15 aminoácidos, objeto de pesquisas pré-clínicas. Fica na vitrine apenas para consulta: não é medicamento registrado na ANVISA, não é vendido pelo site e o rótulo indica uso em pesquisa laboratorial apenas.', 290.0, NULL, NULL, 'Vitrine de estudo', 0, 0, '["Conteúdo: 5mg, pó liofilizado", "Composição: pentadecapeptídeo sintético (15 aminoácidos)", "Conservação: 2-8°C, ao abrigo de luz", "Rótulo: uso em pesquisa laboratorial apenas"]', 1, 1, 0, 1, 1, '{"base": "/loja/bpc-157-5mg", "alt": "Ilustração de frasco de BPC-157 5mg com rótulo Save Concept", "width": 960, "height": 1280}', '["bpc-157", "bpc157", "bpc", "peptideo", "frasco", "5mg", "pesquisa", "estudo"]', '["tb-500-5mg", "ghk-cu-50mg"]', '[]', '2026-09-30T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('tb-500-5mg', 'tb-500-5mg-frasco', 6, 'Save Concept', 'TB-500 5mg', 'Frasco · 5mg, pó liofilizado', 'frascos', 'Fragmento sintético da timosina beta-4 em frasco de 5mg, na vitrine apenas para consulta e estudo.', 'O TB-500 é a versão sintética de um fragmento da timosina beta-4, objeto de pesquisas pré-clínicas. Fica na vitrine apenas para consulta: não é medicamento registrado na ANVISA, não é vendido pelo site e o rótulo indica uso em pesquisa laboratorial apenas.', 320.0, NULL, NULL, 'Vitrine de estudo', 0, 0, '["Conteúdo: 5mg, pó liofilizado", "Composição: fragmento sintético da timosina beta-4", "Conservação: 2-8°C, ao abrigo de luz", "Rótulo: uso em pesquisa laboratorial apenas"]', 1, 1, 0, 1, 1, '{"base": "/loja/tb-500-5mg", "alt": "Ilustração de frasco de TB-500 5mg com rótulo Save Concept", "width": 960, "height": 1280}', '["tb-500", "tb500", "timosina", "thymosin", "peptideo", "frasco", "5mg", "pesquisa", "estudo"]', '["bpc-157-5mg", "ghk-cu-50mg"]', '[]', '2026-09-30T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('ghk-cu-50mg', 'ghk-cu-50mg-frasco', 7, 'Save Concept', 'GHK-Cu 50mg', 'Frasco · 50mg, pó liofilizado', 'frascos', 'Tripeptídeo ligado ao cobre em frasco de 50mg, na vitrine apenas para consulta e estudo.', 'O GHK-Cu é um tripeptídeo (glicil-histidil-lisina) ligado ao cobre, objeto de pesquisas de laboratório. Fica na vitrine apenas para consulta: não é medicamento registrado na ANVISA, não é vendido pelo site e o rótulo indica uso em pesquisa laboratorial apenas.', 250.0, NULL, NULL, 'Vitrine de estudo', 0, 0, '["Conteúdo: 50mg, pó liofilizado", "Composição: tripeptídeo GHK ligado ao cobre", "Conservação: 2-8°C, ao abrigo de luz", "Rótulo: uso em pesquisa laboratorial apenas"]', 1, 1, 0, 1, 1, '{"base": "/loja/ghk-cu-50mg", "alt": "Ilustração de frasco de GHK-Cu 50mg com rótulo Save Concept", "width": 960, "height": 1280}', '["ghk-cu", "ghkcu", "ghk", "cobre", "copper peptide", "peptideo", "frasco", "50mg", "pesquisa", "estudo"]', '["bpc-157-5mg", "tb-500-5mg"]', '[]', '2026-09-30T00:00:00.000Z', 'migration');
