-- Six more peptides for the study showcase (owner's request, 2026-09-30),
-- taking the store to 20 products. Same regime as 0018: category
-- `frascos` (never purchasable: REGULATED_CATEGORIES in the admin API and
-- createOrder), no dosing / route of administration / therapeutic claims,
-- no ratings, no "Compre junto", illustrated images captioned "IMAGEM
-- ILUSTRATIVA". Reference prices are estimates pending the owner's
-- review; edit them in the admin (Loja → Catálogo).
--
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('epitalon-50mg', 'epitalon-50mg-frasco', 8, 'Save Concept', 'Epitalon 50mg', 'Frasco · 50mg, pó liofilizado', 'frascos', 'Tetrapeptídeo sintético em frasco de 50mg, na vitrine apenas para consulta e estudo.', 'O Epitalon é um tetrapeptídeo sintético (Ala-Glu-Asp-Gly), objeto de pesquisas de laboratório. Fica na vitrine apenas para consulta: não é medicamento registrado na ANVISA, não é vendido pelo site e o rótulo indica uso em pesquisa laboratorial apenas.', 280.0, NULL, NULL, 'Vitrine de estudo', 0, 0, '["Conteúdo: 50mg, pó liofilizado", "Composição: tetrapeptídeo sintético (Ala-Glu-Asp-Gly)", "Conservação: 2-8°C, ao abrigo de luz", "Rótulo: uso em pesquisa laboratorial apenas"]', 1, 1, 0, 1, 1, '{"base": "/loja/epitalon-50mg", "alt": "Ilustração de frasco de Epitalon 50mg com rótulo Save Concept", "width": 960, "height": 1280}', '["epitalon", "epithalon", "epithalone", "peptideo", "frasco", "50mg", "pesquisa", "estudo"]', '["semax-10mg", "selank-10mg", "kpv-10mg"]', '[]', '2026-09-30T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('semax-10mg', 'semax-10mg-frasco', 8, 'Save Concept', 'Semax 10mg', 'Frasco · 10mg, pó liofilizado', 'frascos', 'Heptapeptídeo sintético em frasco de 10mg, na vitrine apenas para consulta e estudo.', 'O Semax é um heptapeptídeo sintético análogo de um fragmento do ACTH, objeto de pesquisas de laboratório. Fica na vitrine apenas para consulta: não é medicamento registrado na ANVISA, não é vendido pelo site e o rótulo indica uso em pesquisa laboratorial apenas.', 220.0, NULL, NULL, 'Vitrine de estudo', 0, 0, '["Conteúdo: 10mg, pó liofilizado", "Composição: heptapeptídeo sintético análogo de fragmento do ACTH", "Conservação: 2-8°C, ao abrigo de luz", "Rótulo: uso em pesquisa laboratorial apenas"]', 1, 1, 0, 1, 1, '{"base": "/loja/semax-10mg", "alt": "Ilustração de frasco de Semax 10mg com rótulo Save Concept", "width": 960, "height": 1280}', '["semax", "peptideo", "frasco", "10mg", "pesquisa", "estudo"]', '["epitalon-50mg", "selank-10mg", "kpv-10mg"]', '[]', '2026-09-30T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('selank-10mg', 'selank-10mg-frasco', 8, 'Save Concept', 'Selank 10mg', 'Frasco · 10mg, pó liofilizado', 'frascos', 'Heptapeptídeo sintético em frasco de 10mg, na vitrine apenas para consulta e estudo.', 'O Selank é um heptapeptídeo sintético análogo da tuftsina, objeto de pesquisas de laboratório. Fica na vitrine apenas para consulta: não é medicamento registrado na ANVISA, não é vendido pelo site e o rótulo indica uso em pesquisa laboratorial apenas.', 220.0, NULL, NULL, 'Vitrine de estudo', 0, 0, '["Conteúdo: 10mg, pó liofilizado", "Composição: heptapeptídeo sintético análogo da tuftsina", "Conservação: 2-8°C, ao abrigo de luz", "Rótulo: uso em pesquisa laboratorial apenas"]', 1, 1, 0, 1, 1, '{"base": "/loja/selank-10mg", "alt": "Ilustração de frasco de Selank 10mg com rótulo Save Concept", "width": 960, "height": 1280}', '["selank", "peptideo", "frasco", "10mg", "pesquisa", "estudo"]', '["epitalon-50mg", "semax-10mg", "kpv-10mg"]', '[]', '2026-09-30T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('kpv-10mg', 'kpv-10mg-frasco', 8, 'Save Concept', 'KPV 10mg', 'Frasco · 10mg, pó liofilizado', 'frascos', 'Tripeptídeo sintético em frasco de 10mg, na vitrine apenas para consulta e estudo.', 'O KPV é um tripeptídeo (lisina-prolina-valina), fragmento C-terminal do α-MSH, objeto de pesquisas de laboratório. Fica na vitrine apenas para consulta: não é medicamento registrado na ANVISA, não é vendido pelo site e o rótulo indica uso em pesquisa laboratorial apenas.', 240.0, NULL, NULL, 'Vitrine de estudo', 0, 0, '["Conteúdo: 10mg, pó liofilizado", "Composição: tripeptídeo lisina-prolina-valina (Lys-Pro-Val)", "Conservação: 2-8°C, ao abrigo de luz", "Rótulo: uso em pesquisa laboratorial apenas"]', 1, 1, 0, 1, 1, '{"base": "/loja/kpv-10mg", "alt": "Ilustração de frasco de KPV 10mg com rótulo Save Concept", "width": 960, "height": 1280}', '["kpv", "lys-pro-val", "peptideo", "frasco", "10mg", "pesquisa", "estudo"]', '["epitalon-50mg", "semax-10mg", "selank-10mg"]', '[]', '2026-09-30T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('mots-c-10mg', 'mots-c-10mg-frasco', 8, 'Save Concept', 'MOTS-c 10mg', 'Frasco · 10mg, pó liofilizado', 'frascos', 'Peptídeo de origem mitocondrial em frasco de 10mg, na vitrine apenas para consulta e estudo.', 'O MOTS-c é um peptídeo de 16 aminoácidos codificado no DNA mitocondrial, objeto de pesquisas de laboratório. Fica na vitrine apenas para consulta: não é medicamento registrado na ANVISA, não é vendido pelo site e o rótulo indica uso em pesquisa laboratorial apenas.', 260.0, NULL, NULL, 'Vitrine de estudo', 0, 0, '["Conteúdo: 10mg, pó liofilizado", "Composição: peptídeo sintético de 16 aminoácidos", "Conservação: 2-8°C, ao abrigo de luz", "Rótulo: uso em pesquisa laboratorial apenas"]', 1, 1, 0, 1, 1, '{"base": "/loja/mots-c-10mg", "alt": "Ilustração de frasco de MOTS-c 10mg com rótulo Save Concept", "width": 960, "height": 1280}', '["mots-c", "motsc", "mots", "peptideo", "mitocondrial", "frasco", "10mg", "pesquisa", "estudo"]', '["epitalon-50mg", "semax-10mg", "selank-10mg"]', '[]', '2026-09-30T00:00:00.000Z', 'migration');
--> statement-breakpoint
INSERT OR IGNORE INTO `loja_products` (slug, sku, sort_order, brand, name, presentation, category, summary, description, price, old_price, units_json, badge, rating, review_count, specs_json, free_shipping, available, purchasable, cold_chain, health_notice, image_json, keywords_json, related_json, bought_together_json, updated_at, updated_by) VALUES ('dsip-5mg', 'dsip-5mg-frasco', 8, 'Save Concept', 'DSIP 5mg', 'Frasco · 5mg, pó liofilizado', 'frascos', 'Nonapeptídeo sintético em frasco de 5mg, na vitrine apenas para consulta e estudo.', 'O DSIP é um nonapeptídeo sintético, objeto de pesquisas de laboratório. Fica na vitrine apenas para consulta: não é medicamento registrado na ANVISA, não é vendido pelo site e o rótulo indica uso em pesquisa laboratorial apenas.', 230.0, NULL, NULL, 'Vitrine de estudo', 0, 0, '["Conteúdo: 5mg, pó liofilizado", "Composição: nonapeptídeo sintético (9 aminoácidos)", "Conservação: 2-8°C, ao abrigo de luz", "Rótulo: uso em pesquisa laboratorial apenas"]', 1, 1, 0, 1, 1, '{"base": "/loja/dsip-5mg", "alt": "Ilustração de frasco de DSIP 5mg com rótulo Save Concept", "width": 960, "height": 1280}', '["dsip", "peptideo", "frasco", "5mg", "pesquisa", "estudo"]', '["epitalon-50mg", "semax-10mg", "selank-10mg"]', '[]', '2026-09-30T00:00:00.000Z', 'migration');
