import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
const base='http://127.0.0.1:8787';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1365,height:900},colorScheme:'dark'});
const page=await context.newPage();page.on('response',response=>{if(response.url().includes('/api/session')) console.log('Customer API status:',response.status());});const errors=[];page.on('pageerror',error=>errors.push(error.message));
try {
 await page.goto(base+'/index.html');
 if(await page.locator('#consent-essential').isVisible()) await page.locator('#consent-essential').click();
 await page.getByLabel('Serial do produto',{exact:true}).fill('35172');
 await page.getByRole('button',{name:'Entrar com serial'}).click();
 await page.locator('#login-gate.hidden').waitFor({state:'attached'});
 assert.equal(await page.locator('#user-serial').innerText(),'35172');
 await page.getByLabel('Número de série',{exact:true}).fill('35172');
 await page.getByRole('button',{name:'Consultar serial'}).click();
 await page.locator('#result.authentic').waitFor();
 assert.match(await page.locator('#result').innerText(),/já|adicionado|added|original|autêntico/i);
 await page.goto(base+'/admin');
 await page.locator('#admin-user').fill('admin');
 await page.locator('#admin-password').fill((await readFile(new URL('../.local/.admin-password',import.meta.url),'utf8')).trim());
 await page.getByRole('button',{name:'Entrar no painel'}).click();
 await page.locator('body:not(.admin-locked)').waitFor();
 await page.locator('#verification-log-body tr [data-activity-id]').first().waitFor();
 await page.locator('#verification-search').fill('35172');
 await page.waitForResponse(r=>r.url().includes('/api/admin/dashboard?') && r.url().includes('35172') && r.status()===200);
 assert.match(await page.locator('#verification-log-body').innerText(),/35172/);
 await page.locator('#verification-log-title').evaluate(el => window.scrollTo(0, window.scrollY + el.getBoundingClientRect().top - 195));
 await mkdir(new URL('../outputs/',import.meta.url),{recursive:true});
 await page.screenshot({path:new URL('../outputs/painel-vercel.png',import.meta.url).pathname});
 await page.locator('#verification-log-body [data-activity-id]').first().click();
 await page.locator('#activity-detail-dialog[open]').waitFor();
 assert.match(await page.locator('#activity-detail-content').innerText(),/IP público/);
 assert.match(await page.locator('#activity-detail-content').innerText(),/Não disponível em execução local/);
 await page.screenshot({path:new URL('../outputs/detalhes-acesso.png',import.meta.url).pathname});
 await page.locator('#activity-close').click();
 await page.locator('[data-customer-details="35172"]').first().click();
 await page.locator('#customer-detail-dialog[open]').waitFor();
 assert.match(await page.locator('#customer-detail-content').innerText(),/Origem dos acessos/);
 await page.locator('#close-customer-detail').click();
 await page.setViewportSize({width:390,height:844});
 await page.locator('#verification-log-title').evaluate(el => window.scrollTo(0, window.scrollY + el.getBoundingClientRect().top - 195));
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);assert.equal(overflow,false);
 await page.screenshot({path:new URL('../outputs/painel-vercel-mobile.png',import.meta.url).pathname});
 assert.deepEqual(errors,[]);
 console.log('PASS: browser customer login, duplicate query, admin login, search, event details, profile details, responsive width and no uncaught JavaScript errors.');
} catch(error) { console.log('Page errors:',errors); console.log('Login status:',await page.locator('#login-error').textContent().catch(()=>'')); console.log('Admin status:',await page.locator('#admin-login-error').textContent().catch(()=>'')); await page.screenshot({path:new URL('../outputs/browser-failure.png',import.meta.url).pathname}); throw error; } finally {await browser.close();}
