import assert from 'node:assert/strict';
import { mkdtemp,rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { NextRequest } from 'next/server';
import { getDatabase,closeDatabase } from '../db/client';
import { requestContext } from '../lib/request-context';
import * as adminSession from '../app/api/admin/session/route';
import * as customerSession from '../app/api/session/route';
import * as products from '../app/api/admin/products/route';
import * as profiles from '../app/api/profiles/route';
import * as adminProfiles from '../app/api/admin/profiles/route';
import * as verifications from '../app/api/verifications/route';
import * as benefits from '../app/api/benefits/route';
import * as dashboard from '../app/api/admin/dashboard/route';
import * as audit from '../app/api/admin/audit/route';
import * as qr from '../app/api/admin/qr/route';
import * as sellerContact from '../app/api/seller-contact/route';
import * as adminBenefits from '../app/api/admin/benefits/route';
import { proxy } from '../proxy';
const directory=await mkdtemp(path.join(os.tmpdir(),'vf-postgres-test-'));
delete process.env.DATABASE_URL;delete process.env.VERCEL;
process.env.LOCAL_PG_DIR=path.join(directory,'postgres');process.env.ALLOW_LOCAL_DB='1';
process.env.ADMIN_USER='test-admin';process.env.ADMIN_PASSWORD='integration-only-password';
const base='https://integration.example';
const req=(route:string,body?:unknown,cookie='',headers:Record<string,string>={})=>new Request(base+route,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json',cookie,...headers},body:body===undefined?undefined:JSON.stringify(body)});
const cookie=(response:Response)=>response.headers.get('set-cookie')!.split(';')[0];
try {
 await import('../scripts/migrate-db');
 // Instantiate test database before enabling the simulated Vercel header context.
 getDatabase();
 assert.equal(requestContext(req('/',undefined,'',{'x-forwarded-for':'8.8.8.8','x-vercel-ip-city':'Fake'})).ip,'');
 process.env.VERCEL='1';
 const geo={'x-vercel-forwarded-for':'203.0.113.42','x-vercel-ip-country':'BR','x-vercel-ip-country-region':'SP','x-vercel-ip-city':'S%C3%A3o%20Paulo','x-vercel-ip-latitude':'-23.55','x-vercel-ip-longitude':'-46.63','user-agent':'Mozilla/5.0 (Windows NT 10.0) Chrome/123.0 Safari/537.36','x-vercel-id':'fixture-only','x-vercel-ip-timezone':'America/Sao_Paulo'};
 assert.equal(requestContext(req('/',undefined,'',geo)).city,'São Paulo');
 assert.equal(requestContext(req('/',undefined,'',geo)).browser,'Chrome');
 assert.equal(requestContext(req('/',undefined,'',{'x-vercel-ip-timezone':'Invalid/Zone'})).timezone,'');
 assert.equal((await dashboard.GET(req('/api/admin/dashboard'))).status,401);
 assert.equal((await adminSession.POST(req('/api/admin/session',{user:'test-admin',password:'wrong'},'',geo))).status,401);
 const auth=await adminSession.POST(req('/api/admin/session',{user:'test-admin',password:process.env.ADMIN_PASSWORD},'',geo));
 assert.equal(auth.status,200);assert.match(auth.headers.get('set-cookie')!,/Secure/);const admin=cookie(auth);
 const rows=['88110001','88110002','88110003','88110004','88110005'].map(serial=>({serial,name:'Integration product',maker:'Test',lot:'QA',expiry:'2030',status:'authentic'}));
 assert.equal((await products.POST(req('/api/admin/products',{products:rows},admin,geo))).status,200);
 const login=await customerSession.POST(req('/api/session',{serial:rows[0].serial,metadata:{consent:{analytics:false}}},'',geo));
 assert.equal(login.status,200);const customer=cookie(login);
 const logged=await login.json();assert.equal(logged.profile.products[0].activationTimezone,'America/Sao_Paulo');assert.equal(logged.profile.points,100);assert.equal(logged.credited,true);
 const duplicate=await verifications.POST(req('/api/verifications',{serial:rows[0].serial,status:'invalid',profileId:'other',credited:true},customer,geo));
 assert.equal((await duplicate.json()).credited,false);
 const [a,b]=await Promise.all([verifications.POST(req('/api/verifications',{serial:rows[1].serial},customer,geo)),verifications.POST(req('/api/verifications',{serial:rows[1].serial},customer,geo))]);
 assert.equal([await a.json(),await b.json()].filter(x=>x.credited).length,1);
 const forged=await profiles.POST(req('/api/profiles',{id:'other',points:999999,level:5,benefits:[{code:'FREE'}]},customer,geo));
 assert.equal((await forged.json()).profile.points,200);
 assert.equal((await profiles.GET(req('/api/profiles?id=other',undefined,customer))).status,403);
 assert.equal((await benefits.POST(req('/api/benefits',{threshold:3},customer))).status,409);
 await verifications.POST(req('/api/verifications',{serial:rows[2].serial,metadata:{consent:{analytics:true},timezone:'America/Sao_Paulo',page:'/index.html?secret=hidden'}},customer,geo));
 const reward=await benefits.POST(req('/api/benefits',{threshold:3},customer));assert.equal(reward.status,409);
 const wallet=await (await customerSession.GET(req('/api/session',undefined,customer))).json();assert.equal(wallet.profile.benefits.length,1);const code=wallet.profile.benefits[0].code;await verifications.POST(req('/api/verifications',{serial:rows[2].serial},customer));const again=await (await customerSession.GET(req('/api/session',undefined,customer))).json();assert.equal(again.profile.benefits[0].code,code);
 const otherLogin=await customerSession.POST(req('/api/session',{serial:rows[3].serial},'',geo));const otherCookie=cookie(otherLogin);
 const ownership=await verifications.POST(req('/api/verifications',{serial:rows[0].serial},otherCookie,geo));assert.equal((await ownership.json()).status,'already_claimed');
 const logs=await dashboard.GET(req('/api/admin/dashboard?q=S%C3%A3o%20Paulo',undefined,admin));const payload=await logs.json();
 assert.ok(payload.summary.total>5);assert.equal(payload.records[0].city,'São Paulo');
 assert.equal(payload.records[0].geoSource,'vercel-ip');assert.equal(payload.records[0].ip,geo['x-vercel-forwarded-for']);
 const event=payload.records.find((e:Record<string,unknown>)=>e.serial===rows[0].serial && e.action==='login');assert.equal(event.metadata.timezone,undefined);
 process.env.SELLER_WHATSAPP='5511999999999';
 assert.equal((await sellerContact.GET(req('/api/seller-contact'))).status,401);
 assert.equal((await (await sellerContact.GET(req('/api/seller-contact',undefined,customer))).json()).url,'https://wa.me/5511999999999');
 const beforeRank=await (await adminProfiles.GET(req(`/api/admin/profiles?id=${rows[0].serial}`,undefined,admin))).json();
 await adminProfiles.POST(req('/api/admin/profiles',{...beforeRank.profile,rankOverride:2},admin));
 const rankProfile=await (await customerSession.GET(req('/api/session',undefined,customer))).json();assert.equal(rankProfile.profile.rankCodes.length,1);assert.match(rankProfile.profile.rankCodes[0].code,/^RANK-/);
 const detail=await adminProfiles.GET(req(`/api/admin/profiles?id=${rows[0].serial}`,undefined,admin));const user=await detail.json();assert.equal(user.profile.points,300);
 assert.equal((await adminProfiles.POST(req('/api/admin/profiles',{...user.profile,blocked:true},admin,geo))).status,200);
 assert.equal((await customerSession.GET(req('/api/session',undefined,customer))).status,401);
 assert.equal((await customerSession.POST(req('/api/session',{serial:rows[0].serial},'',geo))).status,401);
 // Monitoring cannot expose admin history to customers or convert its reference into a cookie.
 assert.equal((await audit.GET(req('/api/admin/audit',undefined,otherCookie))).status,401);
 assert.equal((await qr.POST(req('/api/admin/qr',{serial:rows[0].serial,intent:'view'},otherCookie))).status,401);
 const qrResult=await qr.POST(req('/api/admin/qr',{serial:rows[0].serial,intent:'view'},admin));
 assert.equal((await qrResult.json()).path,`/index.html?serial=${rows[0].serial}`);
 await products.POST(req('/api/admin/products',{product:{...rows[0],lot:'UPDATED'}},admin));
 const auditResult=await (await audit.GET(req('/api/admin/audit?q='+rows[0].serial,undefined,admin))).json();
 const change=auditResult.records.find((r:{action:string})=>r.action==='product_updated');
 assert.equal(change.details.before.lot,'QA');assert.equal(change.details.after.lot,'UPDATED');
 assert.ok(auditResult.records.some((r:{action:string})=>r.action==='qr_requested'));
 const cycleProducts=Array.from({length:12},(_,i)=>({...rows[0],serial:String(99110000+i)}));
 await products.POST(req('/api/admin/products',{products:cycleProducts},admin));
 for(const product of cycleProducts) await verifications.POST(req('/api/verifications',{serial:product.serial},otherCookie));
 const cycleProfile=await (await customerSession.GET(req('/api/session',undefined,otherCookie))).json();
 assert.equal(cycleProfile.profile.level,2);assert.equal(cycleProfile.profile.rewardCycle.products,3);
 const cycleReward=cycleProfile.profile.benefits.find((r:{rank:number;threshold:number})=>r.rank===2&&r.threshold===3);
 assert.ok(cycleReward);assert.equal(cycleProfile.profile.rewardCycle.catalog[1].title,'15% de desconto');
 assert.equal((await adminBenefits.POST(req('/api/admin/benefits',{profileId:rows[3].serial,code:cycleReward.code},otherCookie))).status,401);
 assert.equal((await adminBenefits.POST(req('/api/admin/benefits',{profileId:rows[3].serial,code:cycleReward.code},admin))).status,200);
 const repeated=await (await adminBenefits.POST(req('/api/admin/benefits',{profileId:rows[3].serial,code:cycleReward.code},admin))).json();assert.equal(repeated.alreadyRecorded,true);
 const redeemed=await (await customerSession.GET(req('/api/session',undefined,otherCookie))).json();
 assert.ok(redeemed.profile.benefits.find((r:{code:string})=>r.code===cycleReward.code).redeemedAt);
 await customerSession.DELETE(new Request(base+'/api/session',{method:'DELETE',headers:{cookie:otherCookie}}));
 assert.equal((await customerSession.GET(req('/api/session',undefined,otherCookie))).status,401);
 const events=await (await dashboard.GET(req('/api/admin/dashboard',undefined,admin))).json();
 const out=events.records.find((r:{action:string})=>r.action==='logout');
 assert.match(out.metadata.sessionReference,/^[a-f0-9]{24}$/);
 assert.ok(!JSON.stringify(events).includes(otherCookie.split('=')[1]));

 const logout=await adminSession.DELETE(new Request(base+'/api/admin/session',{method:'DELETE',headers:{cookie:admin}}));assert.equal(logout.status,200);
 assert.equal((await dashboard.GET(req('/api/admin/dashboard',undefined,admin))).status,401);
 for(let i=0;i<11;i++) {
  const response=await adminSession.POST(req('/api/admin/session',{user:'bad',password:'wrong'},'',{'x-vercel-forwarded-for':'203.0.113.99'}));
  assert.equal(response.status,i<10?401:429);
 }
 const cross=await proxy(new NextRequest(base+'/api/session',{method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'},body:'{}'}));assert.equal(cross.status,403);
 const huge=await proxy(new NextRequest(base+'/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({x:'a'.repeat(270000)})}));assert.equal(huge.status,413);
 console.log('PASS: PostgreSQL migrations, trusted geo headers, admin/customer sessions, server validation, concurrent duplicate protection, ownership, points tampering, benefit idempotency, profile isolation, geo filters, consent, blocking, revocable logout, throttling and request guards.');
} finally {await closeDatabase();await rm(directory,{recursive:true,force:true});}
